name: Node.js CI
on: [push, pull_request][cite: 1]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3[cite: 1]
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
      - run: npm install[cite: 1]
      - run: npm test[cite: 1]
